site_name: FuckingNode
site_description: The fucking chaos of maintaining JavaScript projects ends here.
site_url: https://zakahacecosas.github.io/FuckingNode/
site_author: ZakaHaceCosas
copyright: Copyright &copy; 2024 - 2025 ZakaHaceCosas

repo_name: ZakaHaceCosas/FuckingNode
repo_url: https://github.com/ZakaHaceCosas/FuckingNode/

docs_dir: "docs"

nav:
    - Home: "index.md"

    - "Why FuckingNode?": "about/why.md"

    - Manual:
          - User manual: "manual/index.md"
          - Installation: "manual/install.md"
          - Configuration: "manual/configuration.md"
          - Main usage guide: "manual/usage.md"
          - Individual project configuration: "manual/fknode-yaml.md"
          - Extra - Kickstart: "manual/kickstart.md"
          - Extra - Commit: "manual/commit.md"
          - Extra - Release: "manual/release.md"
          - Extra - Launch: "manual/launch.md"
          - Extra - Setup: "manual/setup.md"
          - Extra - Stats: "manual/stats.md"
          - Extra - Surrender: "manual/surrender.md"
          - Learn - Cross-runtime support: "learn/cross-runtime-support.md"
          - "What's next?": "manual/whats-next.md"

    - Learn:
          - Learn: "learn/index.md"
          - How does cleanup work under the hood: "learn/clean.md"
          - How does kickstart work under the hood: "learn/kickstart.md"
          - How does audit work under the hood: "learn/audit.md"

    - Roadmap: "about/roadmap.md"
    - Brand guidelines: "about/branding.md"
    - Follow us: "about/social.md"

theme:
    name: material
    custom_dir: docs/overrides

    logo: fkn_logo.png
    favicon: fkn_favicon.png

    features:
        - navigation.path
        - navigation.tabs
        - navigation.sections
        - navigation.top
        - navigation.tracking
        - toc.follow
        - toc.integrate
        - navigation.expand
        - content.code.copy
        - navigation.footer

    palette:
        - scheme: slate
          primary: custom
          accent: custom

extra_css:
    - overrides/extra.css

extra_javascript:
    - js/math.js
    - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
    social:
        - icon: fontawesome/brands/youtube
          link: https://youtube.com/watch?v=_lppvGYUXNk
          name: See us on YouTube!
        - icon: fontawesome/brands/twitter
          link: https://x.com/FuckingNode
          name: Read us on Twitter
        - icon: fontawesome/brands/bluesky
          link: https://bsky.app/profile/fknode.bsky.social
          name: Read us on Bluesky
        - icon: fontawesome/brands/discord
          link: https://discord.gg/AA2jYAFNmq
          name: Chat us on Discord

    analytics:
        provider: custom

plugins:
    - social
    - redirects:
          redirect_maps:
              "about.md": "about/roadmap.md"
              "repo.md": "https://github.com/ZakaHaceCosas/FuckingNode"
              "roadmap.md": "about/roadmap.md"
              "cross-runtime.md": "learn/cross-runtime-support.md"
              "cross-platform.md": "learn/cross-runtime-support.md"
              "crossruntime.md": "learn/cross-runtime-support.md"
              "crossplatform.md": "learn/cross-runtime-support.md"
              "follow-us.md": "about/social.md"

markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - toc:
          permalink: true
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink:
          normalize_issue_symbols: true
          repo_url_shorthand: true
          user: squidfunk
          repo: mkdocs-material
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.snippets
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.blocks.caption
